# Generated by Django 2.1.7 on 2019-02-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='text_discription',
            new_name='text_description',
        ),
    ]
