# Generated by Django 2.1.7 on 2019-02-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_auto_20190227_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date completed'),
        ),
    ]
