# Generated by Django 2.1.7 on 2019-02-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0003_auto_20190227_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_yn',
            field=models.BooleanField(default=False),
        ),
    ]
